Add slider handle snap
jdolan/ObjectivelyMVC pull request #15
Opened 2017-02-05 20:41 UTC by kaadmy

2017-02-06 18:39 UTC, jdolan requested changes

2017-02-06 18:39 UTC, jdolan commented on Sources/ObjectivelyMVC/Slider.c
> +					value = clamp(round(value / this->step) * this->step, this->min, this->max);
This definitely won't work for decimal values / decimal steps.

2017-02-06 18:39 UTC, jdolan commented on Sources/ObjectivelyMVC/Slider.c
> +		self->snapToStep = DEFAULT_SLIDER_SNAP_TO_STEP;
No need to even include this. All instances in Objectively are initialized with `0`, so for things that default to false, I don't even mention them in the initializers.

2017-02-06 18:39 UTC, jdolan commented on Sources/ObjectivelyMVC/Slider.h
> +	 * @brief Enable snapping the sniper handle to the step
"slider" not "sniper" LOL Freudian slip?

2017-02-06 19:19 UTC, kaadmy commented on Sources/ObjectivelyMVC/Slider.c
> +					value = clamp(round(value / this->step) * this->step, this->min, this->max);
I thought they were always doubles?

2017-02-06 19:20 UTC, kaadmy commented on Sources/ObjectivelyMVC/Slider.c
> +		self->snapToStep = DEFAULT_SLIDER_SNAP_TO_STEP;
I had that set to `true` while testing, it's just easier for me.

2017-02-06 19:20 UTC, kaadmy commented on Sources/ObjectivelyMVC/Slider.h
> +	 * @brief Enable snapping the sniper handle to the step
Yeah it was a Fowardian slip.

2017-02-13 00:35 UTC, kaadmy commented on Sources/ObjectivelyMVC/Slider.c
> +					value = clamp(round(value / this->step) * this->step, this->min, this->max);
Unless I'm getting overly confused by this, shouldn't it work?
Did some tests in Python to make sure I'm not going insane:
```
>>> min(max(round(5.6 / 0.5) * 0.5, 1.0), 30.0)
5.5
>>> min(max(round(5.8 / 0.5) * 0.5, 1.0), 30.0)
6.0
>>> min(max(round(8.3 / 0.3) * 0.3, 1.0), 30.0)
8.4
```

As far as I can tell, this should work correctly.

2017-03-25 21:47 UTC, kaadmy commented
Ping @jdolan?

2017-03-25 23:11 UTC, merged